### ISSUE TITLE
Adresa-CZ

### ISSUE THREAD

**Issue by kruzikh** [ncez-cz/cz-core#1]
Zvážit zda nepřidat slice pro číslo popisné a číslo orientační.

**Comment by kruzikh** [comment]
Tohle bychom měli prodiskutovat.
V nynější formě má adresa pouze element $iso21090-ADXP-houseNumber typu string. Může tedy obsahovat jak číslo popisné, tak číslo orientační. Ve standardních [extenzích](http://hl7.org/fhir/extensions/extensions-datatypes.html#Address)  jsem nenašel nic vhodného, takže bychom pravděpodobně museli vytvořit vlastní národní extenzi, resp. extenze pro číslo popisné a číslo orientační. $iso21090-ADXP-houseNumber by potom sloužilo jako kombinace obou čísel.

Vzhledem k tomu, že je navrženo také rozšíření adresy o kód RUIAN, případně také GPS lokaci, může to být už trochu překombinované.

**Comment by petricz** [comment]
V RUIAN má dokonce element AdresniMisto tři položky:
- CisloDomovni - Číslo domovní
- CisloOrientacni - Číselná část čísla orientačního.
- CisloOrientacniPismeno - Koncové písmeno čísla orientačního

Pravidlo pro pořadí při uvádění např. na domech není stanoveno. V různých městech jsou různé zvyklosti. V NIS systémech se často používají 2 pole pro domovní (popisné) a orientační. Už se nepoužívá samostatně písmeno.
V ROB a AISEO se **adresní místo, které je v ČR, odkazuje pouze referencí do RUIAN.** Např. v Zákoně o ZR je u ROB uvedeno:
**§ 18, (1), d)** _adresa místa pobytu[12)](https://www.zakonyprolidi.cz/cs/2009-111#f3973201), případně též adresa, na kterou mají být doručovány písemnosti podle jiného právního předpisu[52)](https://www.zakonyprolidi.cz/cs/2009-111#f3973242); uvedené adresy jsou vedeny ve formě referenční vazby (kódu adresního místa) na referenční údaj o adrese v registru územní identifikace; v případě adresy, na kterou mají být doručovány písemnosti podle jiného právního předpisu[52)](https://www.zakonyprolidi.cz/cs/2009-111#f3973242), se vede i údaj o identifikaci poštovní přihrádky, dodávací schránky nebo poštovním směrovacím číslu místa pobytu anebo adresa, která je mimo území České republiky a které nebyl přidělen kód adresního místa v registru územní identifikace; v případě adresy místa pobytu[12)](https://www.zakonyprolidi.cz/cs/2009-111#f3973201) je tento údaj označen jako adresa úřadu, pokud je stejným způsobem označen v informačním systému evidence obyvatel nebo informačním systému cizinců_

**Comment by kruzikh** [comment]
Rozhodnutí 20.11.2023
Zatím ponecháme bez dodatečného rolišení mezi číslem popisným a orientačním.
