### ISSUE TITLE
Zvážit položku u pacienta - pohlaví a pohlaví při narození

### ISSUE THREAD

**Issue by vecerajindrich** [ncez-cz/cz-core#2]
Stálo by za to rozdělit pohlaví na pohlaví a pohlaví při narození? Viděl jsem to např. v US Core.
https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-patient.html
![image](https://github.com/ncez-cz/cz-core/assets/98391157/f409a82a-d802-45ce-9be3-9c4d2d9103ce)

**Comment by vecerajindrich** [comment]
https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-patient.html

**Comment by petricz** [comment]
Z lékařského pohledu to někdy může mít důvod, pokud některé léčivé přípravky mohou jinak reagovat na jinou hormonální či genetickou podstatu jedince. Ale z praktického pohledu je to v prostředí ČR komplikace, protože tyto dva údaje se nevedou a vede se jen jeden. V dokladech, v registrech apod. se pohlaví "při narození" nevede a bude s tím jen komplikace. Může to být i kulturní a legislativní problém (stát od státu) to vůbec evidovat nebo i zpřístupňovat.

**Comment by kruzikh** [comment]
Požadavek odložíme dokud nebude známo využití informace o pohlaví **při narození**. Bude implementováno rozšíření pro sex-for-clinical-use.
