### ISSUE TITLE
Přidat do adresy kód RUIAN

### ISSUE THREAD

**Issue by kruzikh** [ncez-cz/cz-core#3]
Přidat do adresy kód RUIAN

**Comment by MarekMatejak** [comment]
Adresní místo v RÚIAN: https://vdp.cuzk.cz/vymenny_format/csv/ad-csv-struktura.pdf
Nepovinná extenze adresy by mohla mít hodnotu "Kód ADM", tj. "Kód adresního místa vedeného v Informačním systému územní identifikace (ISÚI).".

**Comment by MarekMatejak** [comment]
Možná pak přidat pravidlo, že pokud bude vyplněn ten RÚIAN kód adresního místa, pak by měla být vyplněna i kompletní struktura (lines, country) i text daného adresního místa.

**Comment by petricz** [comment]
Nejedná-li se o přeshraniční výměnu, pak je při použití adresního místa z RUIAN ve strukturovaných údajích asi nadbytečné uvádět  strukturovaně ostatní údaje. V komunikaci mezi systémy státní správy se předávají jen ty referenční údaje. Možná by pak stačilo uvádět jen celou adresu jako jeden řádek. Ale chápu, že je možná jednodušší pro všechny kombinace případů nedělat výjimky, a prostě co mám ve strukturovaných údajích, tak vyplnit, byť je to možná nadbytečné.

**Comment by kruzikh** [comment]
20.11. Rozhodnuto o relaizace formou extension typu identifier.

**Comment by kruzikh** [comment]
Vytvořil jsem adresní extenzi pro RUIAN viz [https://build.fhir.org/ig/ncez-cz/cz-core/StructureDefinition-cz-address.html](https://build.fhir.org/ig/ncez-cz/cz-core/StructureDefinition-cz-address.html) 
Prosím o kontrolu návrhu

**Comment by kruzikh** [comment]
PRovedeno

**Comment by MarekMatejak** [comment]
Jenom drobný rozdíl v ternínech v dokumentacích. RÚIAN má "adresní místo", ne "adresní bod".

**Comment by kruzikh** [comment]
Přejmenovat extenzi a ověřit, že je použit termín adresní místo nikoliv adresní bod.

**Comment by kruzikh** [comment]
Opraven název extenze na Title: "Adresní místo dle systému RÚIAN (ČÚZK)"
