### ISSUE TITLE
Adresa: Kód země

### ISSUE THREAD

**Issue by kruzikh** [ncez-cz/cz-core#6]
Stanovit omezení na ISO 3166 2? 
Probrat s Giorgio.

**Comment by kruzikh** [comment]
V EU Lan IG je omezení na 2 nebo 3 písmenný kód země. Asi bychom měli ponechat stejně z důvodu kompatibility.

**Comment by kruzikh** [comment]
Dále je k diskusi, zda máme formulovat obecné pravidlo, které by kontrolovalo, zda je v adrese uveden kód země. Zatím je použito pouze u adresy pacienta.

Invariant: cnt-2or3-char
Description: "The content of the country element (if present) SHALL be selected EITHER from ValueSet ISO Country Alpha-2 http://hl7.org/fhir/ValueSet/iso3166-1-2 OR MAY be selected from ISO Country Alpha-3 Value Set http://hl7.org/fhir/ValueSet/iso3166-1-3, IF the country is not specified in value Set ISO Country Alpha-2 http://hl7.org/fhir/ValueSet/iso3166-1-2."
Severity: #warning
Expression: "country.empty() or (country.memberOf('http://hl7.org/fhir/ValueSet/iso3166-1-2') or country.memberOf('http://hl7.org/fhir/ValueSet/iso3166-1-3'))"

**Comment by kruzikh** [comment]
Dle dohody bude kód země omezen na 2 písmenný kód.

**Comment by petricz** [comment]
Kód země (státu) podle ISO 3166-1 alpha-2 je určitě nejvhodnější. Přesto malý doplňující komentář.
Hned v úvodním komentáři je možná chyba. Kód země by měl vycházet z ISO 3166-1, nikoliv z ISO 3166-2, jak je asi v úvodním komentáři uvedeno. Norma -2 je druhou částí normy 3166 a používá se pro rozlišení vnitřního členění států. Je obvykle stanoven standardizací daného státu. Kód územního celku se skládá z 3166-1 alpha-2 a za pomlčkou je pak alfanumerický kód vyjadřující územní část. Příklad: okres Beroun má CZ-202.
Státy, což je náš případ, vychází z ISO 3166-1. Nikde není stanoveno pravidlo pro používání numer-3, alpha-2, alpha-3. A v různých agendových systémech v ČR se používají všechny 3 systémy. ISO doporučuje alpha-2 kód pro obecné použití, alpha-3 pro vyjádření více podobné názvu státu, numer-3 tam, kde je problém s latinkou. Všechny 3 varianty jsou jednoznačné. Vždy určují tentýž stát. Např. RUIAN používá číselné vyjádření numer-3.
Číselník zemí vydávaný ČSÚ je dostupný [zde](https://www.czso.cz/documents/10180/23208652/ciselnik_zemi.xlsx/d5ea8ce6-655c-4bd5-87c2-1a1462754db6?version=1.7).

**Comment by kruzikh** [comment]
Máte pravdu, ono se to trochu plete. Měl jsem napsat ISO 3166-1 alpha 2, byl myšlen dvouznaková kód dle ISO 3166. Ale snad je to už jasné :-)

**Comment by kruzikh** [comment]
Ověřit, zda je szvolený value set kompletní, viz link nahoře.

**Comment by kruzikh** [comment]
číselník zemí dle ČSÚ se zdá být aktuální a obsahuje některé záznamy, které nejsou uvedeny v kódovém systému HL7 iso-3166-1-2. Máme následující možnosti řešení:

1. nechat to na HL7 (např. nebudeme mít Kosovo)
2. vytvořit value set, do kterého vložíme všechny kódy z HL a přidáme chybějící kódy z číselníku ČSÚ (kódový systém ČSU budeme muset také vytvořit).
3. vytvořit nový kódový systém ČSU a číselník odvodit z něj.

Navrhuji realizovat první variantu, protože jde v zásadě o textovou položku, která může obsahovat i kódy mimo připojený číselník.

**Comment by petricz** [comment]
Hlasuji také pro první variantu, tj. nechat to na HL7 iso-3166-1-2. Bude to vyhovovat v 99,999999% případů.
Pokud je Kosovo v číselníku ČSÚ a není v ISO, pravděpodobně je to proto, že Kosovo je uznáno jen 98 členy OSN z celkových 193. ČR je mezi těmi, které Kosovskou Republiku uznali. Mohou to být i ty ostatní případy.
