### ISSUE TITLE
Patient

### ISSUE THREAD

**Issue by kruzikh** [ncez-cz/cz-core#7]
Popsat RID

**Comment by petricz** [comment]
Zatím je RID definován jako 10-timístné číslo, které nesmí začínat "0" (nulou), musí být dělitelné 13 a nesmí být dělitelné 11 (aby se  nedalo zaměnit s rodným číslem). Nejde tedy již zcela o bezvýznamové číslo, mělo by být částečně rozpoznatelné, že jde či nejde o RID, ale neponese žádné osobní údaje.

**Comment by kruzikh** [comment]
Doplněn popis identifikátoru v českém a anglickém jazyce.
